apiVersion: apps/v1
kind: Deployment
metadata:
  name: navigation
  labels:
    app: navigation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navigation
  template:
    metadata:
      labels:
        app: navigation
    spec:
      containers:
      - name: navigation
        image: navigation:0.1.0
        ports:
          - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: NODE_ENV
          value: "production"
        - name: VERSION
          value: 0.1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: navigation
spec:
  selector:
    app: navigation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
